import { Request } from "vineyard-lawn";

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/************************ -- Create User -- *****************************/
	
export interface CreateUserRequest extends Request {
	data: {
	  email: string;
	  password: string;
	}
}


export interface CreateUserResponse {
  email: string;
}


/************************ -- Get User -- *****************************/
	
export interface GetUserRequest extends Request {
	data: {}
}
	

export interface GetUserResponse {
  email: string;
}
