import * as fs from "fs"
import {
  jsonSchema2TsAutoGeneratedText
} from "./json-schema-to-typescript-formatter"

export async function writeTsTypeDefinitions (targetFile: string, endpointTypeDefs: EndpointTypeDef[]): Promise<void> {
  await writeTsDefinitionsPrefix(targetFile)

  for(let i in endpointTypeDefs){
    await writeTsRequestResponseDefinition(targetFile, endpointTypeDefs[i])
  }
}

async function writeTsDefinitionsPrefix(targetFile: string): Promise<void> {
  await fs.writeFileSync(targetFile, "import { Request } from \"vineyard-lawn\";\n\n")
  await fs.appendFileSync(targetFile, jsonSchema2TsAutoGeneratedText)
}

async function writeTsRequestResponseDefinition(targetFile: string, tsDefinition: EndpointTypeDef): Promise<void> {
    const { requestTsDef, responseTsDef, title} = tsDefinition
    await fs.appendFileSync(targetFile, "\n\n/************************ -- "+ title + " -- *****************************/")
    await fs.appendFileSync(targetFile, requestTsDef)
    await fs.appendFileSync(targetFile, responseTsDef)
}

export type EndpointTypeDef = {requestTsDef: string, responseTsDef: string, title: string}